fun main() {

    try {
    } catch (e: Exception) {
        println(e.message)
    }
}
